// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Elevate(arg1:Array<main.Line>):Promise<void>;

export function GetStatus():Promise<main.Status>;

export function Quit():Promise<void>;

export function RunOption(arg1:number,arg2:main.RunOpts):Promise<void>;

export function Scan():Promise<main.Verdict>;
