// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Elevate(arg1) {
  return window['go']['main']['App']['Elevate'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunOption(arg1, arg2) {
  return window['go']['main']['App']['RunOption'](arg1, arg2);
}

export function Scan() {
  return window['go']['main']['App']['Scan']();
}
